[project]
name = "gridworld"
version = "0.1.0"
description = "GridWorld simulation project"
authors = [{ name = "jeeeunkim" }]
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "torch>=2.7.0",
]
